### ISSUE TITLE
Optional level background color

### ISSUE THREAD

**Issue by jacobmcleman** [Trouv/bevy_ecs_ldtk#65]
I've been working on a test project with LDtk, and I've noticed that equal colors that match in LDtk do not match when running in bevy. 
The level background (above the floor) and clear color (below the floor) in this screenshot are both equal to #0D2B45, but when rendered in engine they don't match. Ideally of course, they would match, but I would also be happy with being able to turn off level backgrounds rendering which could allow me to do my own parallax effects for a background in future.

![image](https://user-images.githubusercontent.com/18495239/159604071-42a46465-a7f0-464b-8a62-59eb33f5ad51.png)

**Comment by Trouv** [comment]
Those two colors are very different!

Currently, the plugin should be using the level's background color (not the default level background color) for the background layer of the level, and should be using the editor background color for the clear color (though this will change somewhat in #63). If those are set to the same value, I'd be interested in getting a copy of your ldtk file for testing.

Though like you said, adding an option to LdtkSettings to not set the level background color would probably be a good idea regardless. Similar to #64.

**Comment by jacobmcleman** [comment]
The level file is here [ldtk_test_level.zip](https://github.com/Trouv/bevy_ecs_ldtk/files/8346083/ldtk_test_level.zip)

In case I've missed some files, the repo with the whole project is here https://github.com/jacobmcleman/bevy_platformer/tree/feat/palette-test

**Comment by jacobmcleman** [comment]
I have also produced a minimal repro ldtk file that shows the issue with only one level and nothing placed
[colortest_minrepro.zip](https://github.com/Trouv/bevy_ecs_ldtk/files/8346124/colortest_minrepro.zip)
Screenshot of that project loaded in bevy
![image](https://user-images.githubusercontent.com/18495239/160020867-7cb635e3-33b3-4364-80aa-160cd3a03f1a.png)

**Comment by Trouv** [comment]
I see what's happening. The level background color is being set through bevy_ecs_tilemap, which is accomplished by setting the background layer to have a white image and then setting a single tile on it with its `tile.color` equal to the background color. This same white image is also used for coloring intgrid tiles w/o auto tile rules. But the problem is that the bevy_ecs_tilemap seems to be *blending* the white with the background color. The same is happening to the intgrid tiles, I just didn't notice because the examples I was working off of didn't have such extreme results.

I guess it makes sense for bevy_ecs_tilemap to do that blending. If I could figure out some "identity" image for it to blend with that results in the same color you blend it with, then that would be a quick fix. However, I think we'll have to do something smarter, like generating an image from the LDtk file that has tiles in it for every color that appears in the file, then set the tiles to use that image w/ the appropriate indexes, and not using `Tile::color` at all.

**Comment by Trouv** [comment]
Turns out the blending is *not* intended from bevy_ecs_tilemap, and it should just be multiplying the colors like I expected. This bug has been fixed in bevy_ecs_tilemap's main branch. Try adding this to your `Cargo.toml`:
```toml
[patch.crates-io]
bevy_ecs_tilemap = { git = "https://github.com/StarArawn/bevy_ecs_tilemap", rev = "d5169b6acf96d5f4a88592c3d6d24bde8ad724f6" }
```

**Comment by spoorn** [comment]
@Trouv this is still happening for me using the latest `bevy_ecs_ldtk = "0.5.0"` and `bevy_ecs_tilemap = "0.9.0"`

**Comment by Trouv** [comment]
> @Trouv this is still happening for me using the latest `bevy_ecs_ldtk = "0.5.0"` and `bevy_ecs_tilemap = "0.9.0"`

You're right, this seems to be a regression between `v0.3.0` (`bevy_ecs_tilemap 0.6`) and `v0.4.0` (`bevy_ecs_tilemap 0.7`)

Hoping that #171 will resolve the issue for background images, but it's still a problem for intgrid tiles.

**Comment by spoorn** [comment]
@Trouv can confirm, looks like background is fixed for me

![image](https://user-images.githubusercontent.com/12925899/229037753-624f3e7a-c958-40a8-8e90-a847448ae23c.png)
